### ISSUE TITLE
02-AstroWeightCalculator

### ISSUE THREAD

**Issue by ecrve** [OriginCodeAcademy/Cohort9#7]
1. Where can I find your repository? (Paste a link below)
https://github.com/ecrve/AstroWeightJavaScript
2. What was your best accomplishment in this project?
Getting it to work - making it look cool on a page
3. What was the most challenging piece of this project for you?
The Javascript - get element by ID, connecting the things happening in JS to the things in html to the things on the webpage.

**Comment by michaelerobertsjr** [comment]
Looks like you put the jquery version inside the javascript project or is this the javascript version of the project?  Please make sure you publish two versions of the project, each with the correct names.

Lookup .gitignore, and use it to exclude files like .DS_Store.
